### ISSUE TITLE
Questions about the code of figure7.

### ISSUE THREAD

**Issue by HUNGMINYU** [V2Xgithub/WiLabV2Xsim#10]
I'm sorry to bother you.
I have questions about fig7_simulation.m.
When I try to run this code by matlab,it always failed when its SCS=60.
How to solve it?

![螢幕擷取畫面 2023-02-06 012339](https://user-images.githubusercontent.com/94069259/216834713-e1edff68-95a9-4052-9daf-a7d43768efc1.png)

And if I want to change the value of SCS to test other outputs,how can I change?

Thank you!

**Comment by wzf-cn** [comment]
Hi HUNGMINYU,

Have you changed other parameters? If you simulate with "5G-V2X", the simulator would not run lines 19-20 in the "deriveRanges.m", because these lines are for "IEEE 802.11p".

You could try to set the parameter "Technology" as "5G-V2X". If the error is still there, please give me more details, such as parameter configurations and modifications of the simulator.

**Comment by HUNGMINYU** [comment]
Thanks for your response, I just downloaded the ZIP document and unziped it.
I didn't modify it.
Thank you!
![螢幕擷取畫面 2023-02-07 233737](https://user-images.githubusercontent.com/94069259/217290896-30436c81-f932-451a-aced-91586e5eb845.png)

**Comment by wzf-cn** [comment]
Sorry about this problem, we have updated the method for calculating beacon resource bandwidth of 5G NR-V2X, which causes this problem with the parameter settings of figure 7. In this case, you need to set a smaller "Raw", such as "50", which is not relevant to figure 7.

We need further discussion about this method used in the following line:
https://github.com/V2Xgithub/WiLabV2Xsim/blob/9c8ebaa7cfee5d64b003f6676c10ddcb9d65f712/MatFilesUtilityLTE/deriveBeaconResources.m#L156

You could also download the [prerelease V6.2](https://github.com/V2Xgithub/WiLabV2Xsim/releases/tag/V6.2) to plot figure 7 , which uses the "old" method used in the paper. And the codes for plotting other figures could be found in [current version](https://github.com/V2Xgithub/WiLabV2Xsim/tree/main/codeForPaper)

**Comment by HUNGMINYU** [comment]
Hi,I have a question about different packet size.
If I want to test packet size 150 and 1500, how can I change the value of mcs to get the plot of PRR and distance?
Or I need to change other parameters?
Thank you!!!

**Comment by wzf-cn** [comment]
For the large packet (1500 bytes), you could increase the MCS index one by one to check which is the smallest index with your other settings.

The details of parameter settings could be found in the [Wiki Page](https://github.com/V2Xgithub/WiLabV2Xsim/wiki/2.-Tutorial#22-parameters).

**Comment by HUNGMINYU** [comment]
Thanks for your responds!!!
I want to ask that the parameter of config and simulation file.
Simulation:
packetSize=350
Raw=150
rho=100
MCS_NR=21

Config:
packetSize=190
Raw=300
rho=35.5
MCS_NR=7

Why they are different?
If I want to change the parameters, do I need to change the parameters of both files?


And I want to ask that the meaning of the parameter "Raw".
When I change the value of Raw, its results were different. 
I also want to know that my computer can run result successfully sometimes when Raw=150, but it failed sometimes.
Why would it run successfully when its Raw is 50?

Thanks for your responds a lot!!!

**Comment by wzf-cn** [comment]
1. You could set parameters in three ways as given in the [wiki page](https://github.com/V2Xgithub/WiLabV2Xsim/wiki/2.-Tutorial#22-parameters):
 (1) change the default parameter in the simulator;
 (2) set the parameters in the config file;
 (3) set the parameters with Arguments when you call the function "WiLabV2Xsim"
The priority of these three ways is: (3)>(2)>(1). And if there is a confliction for a parameter, the one with higher priority would work.

2. The "Raw" is the range you are interested, simulator would counting the related results within this range. You could also find some examples in the [wiki page](https://github.com/V2Xgithub/WiLabV2Xsim/wiki/Output-File-Format-Description).

3. The "Raw" should not larger than the maximum Transmission Range with the given scenario, or the simulator would throw out an error, as you can see in the simulator.
 (1) https://github.com/V2Xgithub/WiLabV2Xsim/blob/5a68a75a2d2435d96fef56b1f78c3ba23c58f142/MatFilesSINR/deriveRanges.m#L19
 (2) https://github.com/V2Xgithub/WiLabV2Xsim/blob/5a68a75a2d2435d96fef56b1f78c3ba23c58f142/MatFilesSINR/deriveRanges.m#L33

**Comment by HUNGMINYU** [comment]
OK.
I learn a lot from your answer.
Thank you for your responds!!!
