### ISSUE TITLE
Adding configurable custom delay to messages + End-to-End Delay

### ISSUE THREAD

**Issue by hullspokes** [V2Xgithub/WiLabV2Xsim#12]
Hello,

first of all thank you for providing the simulator. It is really great.
I have already played around with it a bit.

Now I have the following use case:

I would like to create some evaluations and graphs under IEEE 802.11p. This is simply adding a delay for different user counts (to simulate the runtime of the protocol). 

My question now would be, where is the best place to add this custom delay to possibly integrate it directly into the simulation.
Would the `packetDuration11p(Nbyte,Mode,NbitsHz,BwMHz,pWithLTEPHY)` function be the right place here?

Also, it would be interesting to know how I can output the end-to-end delay shown in the tutorial. Somehow I can only find the options for the Data Age (`printDataAge`) as well as the Inter Packet Gap (`printUpdateDelay`). 
Is this maybe the `printPacketDelay` setting?
Because this is somehow unclear to me... In the document it says:
"...between the generation of the packet and its effective transmission..."
But what I would assume to be the end-to-end delay is between the generation of the packet and its effective reception.

Thank you very much in advance.

**Comment by wzf-cn** [comment]
Hi!

(a) For the custom delay, maybe you could rewrite the function "startNewBackoff11p.m", which would calculate the backoff time for all vehicles.

(b) You could set "printPacketDelay" to print the End-to-End delay (EED), for other outputs, you may want to check the [wiki page](https://github.com/V2Xgithub/WiLabV2Xsim/wiki/Output-File-Format-Description). And what you understand is right, the EED is the duration between the packet generation and its effective reception.

**Comment by hullspokes** [comment]
Great thank you, I will definitely try that.

One more question:
I would need to scale my custom delay based on the number of users affected.
What is the easiest way to get the current user count in the `startNewbackOff11p.m`?
Can I just use the `stationManagement.allNeighborsID`?


Ahja and what is also a bit unclear to me is the `nTransm` parameter. Does this mean the number of general trasmissions? So if it is 1 each client sends exactly one message or how is the parameter to be understood?

Thank you, I have visited the wiki page before. This is really very helpful.

And thanks for the quick answer.

**Comment by wzf-cn** [comment]
Hi!

1. Because you are evaluating 11p, there are 2 parameters that might be related:
  - `stationManagement.neighborsID11p`: It's a 2-D matrix, and logs the neighbors of each vehicle within the max transmission range; Please see:
https://github.com/V2Xgithub/WiLabV2Xsim/blob/70c891ca344a3d4fad5745142c34ab1ee5dd27b2/MatFilesUtility/computeNeighbors.m#L82
  - `stationManagement.awarenessID11p`: It's a 3-D matrix, similar to the one above. The neighbors of each of the interested ranges (could be set with parameter `Raw`) would be logged with each 3rd dimension index. For example, if you set `Raw` as `[50, 100, 150]` meters,   `stationManagement.awarenessID11p(:,:,2)` is all neighbor IDs within 100 meters. Please see:
https://github.com/V2Xgithub/WiLabV2Xsim/blob/70c891ca344a3d4fad5745142c34ab1ee5dd27b2/MatFilesUtility/computeNeighbors.m#L88

2. If I'm right, this parameter is not relevant in your case. Because `nTransm` is related to the parameter `cv2xNumberOfReplicasMax`, which is only used in the LTE/NR-V2X cases. You could remove this "name, value" pair or just ignore them.
 - We have also implemented retransmissions of 11p in the simulator, you could [find related paper link and code here](https://github.com/V2Xgithub/WiLabV2Xsim/tree/main/codeForPaper/Zhuofei2023Repetition)
   -  Several related parameters could be set, such as `retransType`, `ITSNumberOfReplicasMax`, `ITSRetransBackoffInterval`, `ITSReplicasThreshold1`, and so on. 
   - I'm sorry that we haven't updated the input parameters, but when you search these parameters in the file `initiatePhyParameters.m`, you maybe find some comments.
   - Currently, only the output metrics PRR and CBR are updated to fit this case, others may output wrong values.

**Comment by hullspokes** [comment]
Thanks, the `stationManagement.neighborsID11p` and `stationManagement.awarenessID11p` info helped. 
I now got my custom delay correctly implemented depending on the number of vehicles in the awareness range.

Regarding the number of transmissions. Is there a setting to set or configure the total number of messages to be sent? Or is sending data in the simulation just an endless event during the simulation duration?  

Where I'm currently still struggling is with the printing of the End-to-End delay in the `printPacketDelay` section.
Is the EED already somewhere available or do I need to compute it? And if so how am I going to do this?

Sorry for all the questions, but I don't know the code well enough to figure it all out myself.
Therefore your help is really great! Thanks here again for that.

**Comment by wzf-cn** [comment]
Hi!

We don't have parameters to control the total number of messages. Vehicles will send data periodically or following the CAM rules during the whole simulation time.

When you set the `printPacketDelay` as true, you could find a file named like "packet_delay_*.xls" file in your output folder. 

And from your question, I think the explanation of this part in our [wiki page](https://github.com/V2Xgithub/WiLabV2Xsim/wiki/Output-File-Format-Description) may not be very clear to new users, please help us improve it. Thanks!

**Comment by hullspokes** [comment]
All right, thanks for the clarification.

Ah ok, sorry I had misunderstood something. I thought the printPacketDelay does not represent the End-To-End Delay and it would be necessary to have some additional code to calculate it. From the slides in the tutorial it is not quite obvious.
But now everything is clear.

**Comment by hullspokes** [comment]
I'm now still a bit lost in interpreting the results of the `printPacketDelay` output.
Probably that's because I'm not understanding the `delayResolution`.
I can't find any real explanation in the tutorial documents, in the wiki or in the source code.

As far as I understand it, it is the default delay set for messages in the simulation. What I don't understand is why this varies from 0.0010 to 0.1. And after that the packet numbers are always 0 and the CDF is 1.

With the result below, I don't know how to make statements about the message delay.
In general I would expect a stable delayResolution. With that I would then compare the CDF based on the number of packets sent.

Or is this variation intended and I just have to combine several simulations for a certain delayResolution?  
And if so, what would be a typical acceptable value to get a realistic simulation?

Results from the printPacketDelay csv:
```
0.0010   18.0000    0.0111
0.0020   40.0000    0.0356
0.0030   26.0000    0.0516
0.0040   30.0000    0.0701
0.0050   16.0000    0.0799
0.0060   15.0000    0.0891
0.0070    9.0000    0.0947
0.0080   25.0000    0.1100
0.0090   12.0000    0.1174
0.0100    7.0000    0.1217
0.0110   19.0000    0.1334
0.0120   13.0000    0.1414
0.0130   20.0000    0.1537
0.0140   16.0000    0.1635
0.0150   12.0000    0.1709
0.0160   29.0000    0.1887
0.0170   52.0000    0.2207
0.0180   19.0000    0.2323
0.0190    9.0000    0.2379
0.0200   20.0000    0.2502
0.0210    7.0000    0.2545
0.0220   14.0000    0.2631
0.0230   14.0000    0.2717
0.0240   11.0000    0.2784
0.0250   10.0000    0.2846
0.0260   15.0000    0.2938
0.0270   17.0000    0.3042
0.0280   11.0000    0.3110
0.0290   16.0000    0.3208
0.0300   11.0000    0.3276
0.0310   13.0000    0.3356
0.0320   13.0000    0.3436
0.0330   31.0000    0.3626
0.0340   20.0000    0.3749
0.0350   12.0000    0.3823
0.0360   14.0000    0.3909
0.0370   11.0000    0.3977
0.0380   14.0000    0.4063
0.0390   19.0000    0.4179
0.0400   14.0000    0.4266
0.0410   14.0000    0.4352
0.0420   13.0000    0.4431
0.0430   23.0000    0.4573
0.0440   17.0000    0.4677
0.0450    8.0000    0.4726
0.0460   17.0000    0.4831
0.0470   20.0000    0.4954
0.0480   27.0000    0.5120
0.0490   18.0000    0.5230
0.0500   12.0000    0.5304
0.0510   11.0000    0.5372
0.0520   16.0000    0.5470
0.0530   11.0000    0.5538
0.0540   14.0000    0.5624
0.0550   36.0000    0.5845
0.0560   11.0000    0.5913
0.0570   21.0000    0.6042
0.0580   15.0000    0.6134
0.0590   10.0000    0.6195
0.0600   15.0000    0.6288
0.0610    7.0000    0.6331
0.0620   10.0000    0.6392
0.0630   12.0000    0.6466
0.0640   14.0000    0.6552
0.0650   17.0000    0.6656
0.0660    5.0000    0.6687
0.0670    9.0000    0.6742
0.0680    4.0000    0.6767
0.0690   14.0000    0.6853
0.0700   29.0000    0.7031
0.0710   20.0000    0.7154
0.0720   19.0000    0.7271
0.0730   18.0000    0.7382
0.0740   23.0000    0.7523
0.0750   18.0000    0.7634
0.0760   10.0000    0.7695
0.0770    6.0000    0.7732
0.0780    6.0000    0.7769
0.0790    9.0000    0.7824
0.0800   20.0000    0.7947
0.0810    6.0000    0.7984
0.0820   20.0000    0.8107
0.0830    9.0000    0.8162
0.0840   14.0000    0.8248
0.0850   52.0000    0.8568
0.0860   15.0000    0.8660
0.0870   15.0000    0.8752
0.0880   17.0000    0.8857
0.0890   31.0000    0.9047
0.0900    9.0000    0.9103
0.0910    6.0000    0.9140
0.0920    7.0000    0.9183
0.0930   10.0000    0.9244
0.0940    8.0000    0.9293
0.0950   12.0000    0.9367
0.0960   12.0000    0.9441
0.0970   18.0000    0.9551
0.0980   15.0000    0.9644
0.0990    7.0000    0.9687
0.1000   51.0000    1.0000
0.1010         0    1.0000
0.1020         0    1.0000
0.1030         0    1.0000
0.1040         0    1.0000
0.1050         0    1.0000
0.1060         0    1.0000
0.1070         0    1.0000
0.1080         0    1.0000
0.1090         0    1.0000
0.1100         0    1.0000
0.1110         0    1.0000
0.1120         0    1.0000
0.1130         0    1.0000
0.1140         0    1.0000
0.1150         0    1.0000
0.1160         0    1.0000
0.1170         0    1.0000
0.1180         0    1.0000
0.1190         0    1.0000
0.1200         0    1.0000
0.1210         0    1.0000
0.1220         0    1.0000
0.1230         0    1.0000
0.1240         0    1.0000
0.1250         0    1.0000
0.1260         0    1.0000
0.1270         0    1.0000
0.1280         0    1.0000
0.1290         0    1.0000
0.1300         0    1.0000
0.1310         0    1.0000
0.1320         0    1.0000
0.1330         0    1.0000
0.1340         0    1.0000
0.1350         0    1.0000
0.1360         0    1.0000
0.1370         0    1.0000
0.1380         0    1.0000
0.1390         0    1.0000
0.1400         0    1.0000
0.1410         0    1.0000
0.1420         0    1.0000
0.1430         0    1.0000
0.1440         0    1.0000
0.1450         0    1.0000
0.1460         0    1.0000
0.1470         0    1.0000
0.1480         0    1.0000
0.1490         0    1.0000
0.1500         0    1.0000
0.1510         0    1.0000
0.1520         0    1.0000
0.1530         0    1.0000
0.1540         0    1.0000
0.1550         0    1.0000
0.1560         0    1.0000
0.1570         0    1.0000
0.1580         0    1.0000
0.1590         0    1.0000
0.1600         0    1.0000
0.1610         0    1.0000
0.1620         0    1.0000
0.1630         0    1.0000
0.1640         0    1.0000
0.1650         0    1.0000
0.1660         0    1.0000
0.1670         0    1.0000
0.1680         0    1.0000
0.1690         0    1.0000
0.1700         0    1.0000
0.1710         0    1.0000
0.1720         0    1.0000
0.1730         0    1.0000
0.1740         0    1.0000
0.1750         0    1.0000
0.1760         0    1.0000
0.1770         0    1.0000
0.1780         0    1.0000
0.1790         0    1.0000
0.1800         0    1.0000
0.1810         0    1.0000
0.1820         0    1.0000
0.1830         0    1.0000
0.1840         0    1.0000
0.1850         0    1.0000
0.1860         0    1.0000
0.1870         0    1.0000
0.1880         0    1.0000
0.1890         0    1.0000
0.1900         0    1.0000
0.1910         0    1.0000
0.1920         0    1.0000
0.1930         0    1.0000
0.1940         0    1.0000
0.1950         0    1.0000
0.1960         0    1.0000
0.1970         0    1.0000
0.1980         0    1.0000
0.1990         0    1.0000
0.2000         0    1.0000
```

**Comment by wzf-cn** [comment]
Hi!

The `delayResolution` is the width of each “bar” of the “bar chart” and is used for counting the event numbers whose EED falls into the related bars.

Which technology are you using, or what special parameters have you set? Because from the EED log, it is more likely that you are using LTE rather than 11p.

When the CDF reaches 1 at a specific delay time _t_, that means there are no packet delays larger than _t_.

**Comment by hullspokes** [comment]
Ah ok now I'm getting it. So the delayResolution say's like there are n number of packets with that amount of specific delay, right?

I'm having currently the following config file:

```
[simulationTime]                    120
[Technology]	                    80211p
[TypeOfScenario]	            ETSI-Highway
[roadLength]	                    3000
[roadWidth]	                    4
[vMean]                             120
[vStDev]                            12
[NLanes]                            3
[rho]                               5 %density of vehilces per km

[beaconSizeBytes]                   350
[averageTbeacon]                    0.1
[variabilityGenerationInterval]     0
[retransType]                       0
[ITSRetransBackoffInterval]         32              % [us] length of SIFS
[dcc_active]                        false

[sizeSubchannel]        10
[raw]                  [50]

%[folderPERcurves]	PERcurves/G5-UrbanLOS
%[folderPERcurvesNLOS]	PERcurves/G5-CrossingNLOS

[F_dB]	                            6

[rilModel11p]	                    true
[channelModel]                      0
[MCS_11p]                           2

% output
[printUpdateDelay]      true
[printPacketDelay]      true
```

Probably my custom delay in the NewBackoff function is causing that behaviour.
Because without my modification the EED log looks like this:

```
0.0010 | 9572 | 0.968826
0.0020 | 308 | 1.000000
```

I'm modified it like the following:

```Matlab
function [nSlot, timeNextTxRx] = startNewBackoff11pCustomDelay(timeNow,CW,tAifs,tSlot,vehiclesInRange)
% Function that performs backoff in IEEE 802.11p
nSlot = randi(CW);

% Set parameters
base_delay = 340e-03; % base delay for 1 attendees
k = 0.02; % exponential growth rate

% Define function
delay_func = @(n) base_delay * exp(k*n);
totalNumVehicles = numel(nonzeros(vehiclesInRange));

% TODO: Enhance algorithm for calculating delay depending on totalNumVehicles
overallAttestationDelay = delay_func(totalNumVehicles);

timeNextTxRx = timeNow + overallAttestationDelay + tAifs + nSlot * tSlot;
```


Maybe I should add my delay somewhere different.
Because the delay should normally only be added in an initial let's say "grouping-phase".
Either directly at the simulation start or maybe even better, when a car is entering the awareness/interest range.
Is this somehow possible to add a let's say "guard" to monitor the `stationManagement.awarenessID11p` matrix and on change trigger the custom delay adding to all the next messages to be sent in that awareness range? 
And at what place should the delay then be inserted in the code?

**Comment by wzf-cn** [comment]
Hi!

(1) For the EED, actually, the simulator cumulates the event rather than the packet number. For example, if the transmitter generated a packet at time $t$ and only $n$ of its neighbors received the packet at $t+\Delta t$ (we ignore the signal **propagation time** (on air) in the simulator), then the bar that contains the $\Delta t$ would plus $n$.

(2) The `stationManagement.awarenessID11p` is only updated in the function "computeNeighbors", which is called after the position update function, so you could add a monitor after it, e.g. after line 89
https://github.com/V2Xgithub/WiLabV2Xsim/blob/70c891ca344a3d4fad5745142c34ab1ee5dd27b2/MatFilesUtility/computeNeighbors.m#L89

**Comment by VittorioTodisco** [comment]
Closed.
