### ISSUE TITLE
关于NR-V2X技术下设置消息为单播，多播，广播的问题和设置消息发送优先级的问题

### ISSUE THREAD

**Issue by Hui-yes** [V2Xgithub/WiLabV2Xsim#13]
您好，我想请问一下
（1）NR-V2X技术下您的模拟器里怎么设置传递的消息为单播，多播，广播。
（2）NR-V2X技术下您的模拟器里怎么设置传递消息优先级。
补充：我目前在复现https://ieeexplore.ieee.org/document/9443357 这篇论文的结果，卡到这儿了。期待您的回复，万分感谢。

**Comment by wzf-cn** [comment]
您好！
(1) 我们的模拟器目前只能设置广播模式，单播和多播尚未开发
(2) 我们的模拟器不支持多种优先级的设置，默认所有消息有相同的优先级。

**Comment by Hui-yes** [comment]
非常感谢您的回复，此外，我想请教下，仿真器关于盲重传和基于反馈的重传是怎样设置的？

**Comment by wzf-cn** [comment]
1. 我们尚未实现基于反馈的重传。
2. 对于NR-V2X的盲重传，你可以通过参数`cv2xNumberOfReplicasMax`来设置，重传包所需的时频资源由前一个包在发送时预留。

**Comment by Hui-yes** [comment]
好的，谢谢您的耐心解答。
