### ISSUE TITLE
Questions about the meaning of input parameters

### ISSUE THREAD

**Issue by Hui-yes** [V2Xgithub/WiLabV2Xsim#14]
Good afternoon! 
As shown in the following figure,
![image](https://user-images.githubusercontent.com/129721380/231071107-e8065b68-6623-460f-88a4-c147baa26525.png)
(1)Does this parameter represent the number of retransmissions?
(2)The table shows "HARQ".How does this parameter relate to HARQ？
I would be grateful if I could get an answer.

**Comment by wzf-cn** [comment]
Hi Hui-yes!

(1) Yes, the parameter `cv2xNumberOfReplicasMax` represent the number of retransmissions of CV2X;

(2) In the simulator, "HARQ" is also used to refer to retransmissions. When the retransmission was activated, the transmitter would retransmit the same message (broadcast) without feedback from the receiver. This was named "blind HARQ" in [Qualcomm's document](https://www.qualcomm.com/content/dam/qcomm-martech/dm-assets/documents/c-v2x_technical_performance_faq.pdf). 
 
Furthermore, the two messages would be encoded somehow differently by the transmitter to increase the diversity. And the receiver would use maximum ratio combining (MRC) to jointly determine the received messages:

$$\text{SINR}_\text{MRC}=\sum_{i=1}^n\text{SINR}_i$$

Where $\text{SINR}_i$ is the $i$-th SINRs of the replicate message received from the same transmitter.
Without the MRC, the $i$-th message could only determined by $\text{SINR}_i$

**Comment by Hui-yes** [comment]
Hello,
I have a question. In the actual use of the Internet of vehicles, periodic data and aperiodic data exist at the same time, so how should we set this situation? OR we can only set one of them?
I would be grateful if I could get an answer.

**Comment by VittorioTodisco** [comment]
At the moment in the available version of the simulator you can either simulate periodic or aperiodic traffic by specifying the parameters: "allocationPeriodc", "generationInterval" and "generationIntervalAverageRandomPart".
