### ISSUE TITLE
LTE based V2X Scenario by using CARLA  

### ISSUE THREAD

**Issue by melihyazgan** [V2Xgithub/WiLabV2Xsim#18]
Hi all,
I would like to ask about the integration of your Sim Environment in Carla.
It is clear that SUMO can run under Carla's hood. As I understand from wiki your tool runs with SUMO. What do you think about the integration of these in CARLA? Do you have any experience with it?

Thanks in advance

**Comment by VittorioTodisco** [comment]
Hello,
Thanks for showing interest in our work!
We are indeed expanding the support for SUMO in our simulator.
At the moment we don't have enough resources to work on integration with other simulators but we might consider discussing it.
I'll write you an email.

Regards.
Vittorio
