### ISSUE TITLE
questions about IBE calculation

### ISSUE THREAD

**Issue by ZeeSSSean** [V2Xgithub/WiLabV2Xsim#19]
Hello!
Thanks to provide this excellent project. I have some questions about IBE calculation in **IBEcalculation.m**.

**Q1**: Why P_RB_dBm = 0 in line 190? In TS 36.101(LTE) or TS 38.101(NR), P_RB means average transmitted power. Doesn't it need to correlate with the set transmit power?

**Q2**: Why need to subtract 30 from the last item in line 192 and line 194? There is no such operation in Table 6.5.2A.3.1-1 of TS 36.101 and Table 6.4A.2.1.2-1 of TS 38.101.

**Q3**: Why are IQ image and carrier leakage calculated differently than those in TS? Output power is considered in TS, but not in IBEcalculation.m.

Thank you all!

**Comment by VittorioTodisco** [comment]
Hello,

I'll try to answer the first two points quickly, and I can return to it later if needed.
Please note that IBEcalculation.m has been written according to a previous version of the TS, which might have changed slightly over time.

1)  P_RB_dBm refers to the transmitting power over a resource block, which must be considered according to the TS as -30 dB. However, the transmitting power could be less in the particular simulation instance.
-30 dB of power becomes 0 dBm of P_RB_dBm.

2) The terms from lines 192 and 194 are in dB. But at the end of the equations we are considering powers in dBm, therefore by subtracting 30 they become power in dB.

**Comment by ZeeSSSean** [comment]
Hi Vittorio, thanks your reply!
It should be noted that the TS I consulted matches the version given at line 5 of IBEcalculation.m, i.e. TS 38.101-1 V17.0.0 (2020-12).

1. I cannot find the statement about the P_RB_dBm having to be -30 dB in TS 38.101-1. In note 10 of Table 6.4A.2.1.2-1, "P_RB is an average of the transmitted power over 10 sub-frames normalized by the number of allocated RBs, measured in dBm". May I have the detail information about the P_RB_dBm having to be -30 dB?
2. According to the usage of IBEmatrixData at line 89 in initLastPowerCV2X.m, it seems like some kind of **ratio** to calculate interference power. From the perspective of unit, the first two terms have no unit, representing ratio. How come the third term represents power? I am a little comfused about this point :(

**Comment by VittorioTodisco** [comment]
Hi, sorry for getting back to you this late, but I finally had time to return to this question.

Indeed, the point you brought up is correct.

Firstly, the IBE is a ratio of the power spilled in a RB outside the transmitting RBs and the power in a transmitting RB.
So by multiplying the transmitting power for the IBE in a certain resource block, you get the emitted power in that resource block.

Therefore as you point out, the term in the IBE calculation should be in dB.

Moreover, note that when we express a transmitting power over a fixed bandwidth, is generally expressed in dBm (i.e. the tx power is 23dBm over a 10MHz bandwidth). We consider power densities when the bandwidth can vary.

1. As you mentioned, I couldn't find any statement in the standard mentioning a fixed power for P_RB_dBm. In addition, I believe the division in the equation reported in the standard is not correct (57/180e3). 57 is a power in dBm referred to the RB bandwidth of 180kHz. In fact, the division is not present anymore in later specifications. Nevertheless, regardless of the set power for P_RB_dBm, the term in which P_RB_dBm appears is never the biggest one. Therefore we can set it to the max possible value which is 23dBm over one subchannel. So 13dBm over a RB.
I will correct the term to the latest specified version: -57+10*log10(SCS/15)-P_RB_dBm

2. The standard mentions that the IBE limit should be the highest between P_RB_dBm -30 and the power sum of the three terms (general, IQ, CL). Nevertheless, the biggest term is always P_RB_dBm -30. We do not consider this max operation to avoid overestimating the IBE.

2.  Keep in mind that in the simulator we consider resources on a subchannel basis. Therefore we average the IBE evaluated for each RB over the different subchannels and obtain an IBE matrix on a subchannel basis.

**Comment by ZeeSSSean** [comment]
Now I can understand it.
Thank you so much for your response!
