### ISSUE TITLE
About using the new map

### ISSUE THREAD

**Issue by ysj4242** [V2Xgithub/WiLabV2Xsim#20]
I would like to create a map using an actual map and simulate it. Could you please tell me how to apply it?
thank you

**Comment by V2Xgithub** [comment]
Hi, 
actually you cannot directly import a map inside the simulator to reproduce the vehicle movements. 
However, you can use SUMO for this scope and link SUMO to the simulator: SUMO is a traffic simulator that you can use to generate the mobility of the vehicles, by also importing external maps; the positions of the vehicles in consecutive instants (by default it is every 100 ms) are then imported in WiLabV2Xsim. 
More information on how to link SUMO with the simulator can be found in the WiKi of github. 
Best regards

**Comment by ysj4242** [comment]
Thank you for response.
