### ISSUE TITLE
Non existent matlab function

### ISSUE THREAD

**Issue by phaneendra-vidu** [V2Xgithub/WiLabV2Xsim#26]
mco_initiateParameters(fileCfg,appParams,phyParams,varargin{1}) does not exist in InitiateSpecificParameters.m function

Please update

Thanks
Regards
Phaneendra

**Comment by caspycat** [comment]
did you add all the `MatFiles` folder in the project to the project's matlab path?

**Comment by phaneendra-vidu** [comment]
> did you add all the `MatFiles` folder in the project to the project's matlab path?

Yes. I did. I tried to search for function mco_initiate(fileCfg,appParams,phyParams,varargin{1}). 
But I cannot see that in the list. 
Awaiting your reply

Thanks

**Comment by V2Xgithub** [comment]
Sorry,
the files related to multi-channel operations (MCO) have not been yet included in the open version.
The simulator works also without them, except that you cannot use that specific functionality.
Please contact me directly via email if you are interested to MCO.
Best regards

Alessandro Bazzi, Ph.D.
Associate Professor @ DEI, Università di Bologna
Associated with WiLab, CNIT
www.alessandrobazzi.com<http://www.alessandrobazzi.com/>
Phone: +39-051-2093880
________________________________
Da: V4MayaBommalu ***@***.***>
Inviato: martedì 10 ottobre 2023 15:35
A: V2Xgithub/WiLabV2Xsim ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: Re: [V2Xgithub/WiLabV2Xsim] Non existent matlab function (Issue #26)


did you add all the MatFiles folder in the project to the project's matlab path?

Yes. I did. I tried to search for function mco_initiate(fileCfg,appParams,phyParams,varargin{1}).
But I cannot see that in the list.
Awaiting your reply

Thanks
