### ISSUE TITLE
Matlab Version and Required Toolboxes

### ISSUE THREAD

**Issue by tfehren** [V2Xgithub/WiLabV2Xsim#3]
What are the requirements to run the simulator?

In detail:
- Matlab Version
- Toolboxes required
- Octave compatible?
- other requirements

**Comment by VittorioTodisco** [comment]
The code runs correctly with the versions from 2021b at least. 
There are problems with version 2016b and earlier. With the versions in between, some minor corrections would be required (we haven't checked all the versions).
We are checking if it works with Octave.

The Statistics and Machine Learning Toolbox™ is needed for the simulation and generation of 3GPP a-periodic traffic.

**Comment by wzf-cn** [comment]
The Octave compatible version was uploaded as a new branch.

**Comment by tfehren** [comment]
Thanks for the quick reply. Will check the Octave version :)
