### ISSUE TITLE
Question About Blind Retransmission

### ISSUE THREAD

**Issue by ysj4242** [V2Xgithub/WiLabV2Xsim#34]
I hope this message finds you well. I am currently using a simulator and have encountered a question regarding its functionalities. Specifically, I am interested in implementing the blind retransmission feature. I was wondering if setting the variable 'cv2xNumberOfReplicasMax' would accomplish this. I noticed that this variable cannot exceed 3. Does this mean that it is not possible to implement more than three repetitions?
I would greatly appreciate it if you could provide me with some tips regarding this matter.
Thank you for your time and assistance.

**Comment by VittorioTodisco** [comment]
Hello,
yes, the currently available version already includes blind retransmissions up to a maximum of 1 retransmission.
Please set 'cv2xNumberOfReplicasMax' equal to two.
There are small differences between LTE and NR. For example, in NR the first transmission reserves the second transmission.
Both resources also reserve the future allocation according to the SPS scheme.

Let me know if you encounter any issue.

**Comment by VittorioTodisco** [comment]
.

**Comment by ysj4242** [comment]
Hello, I have a new question. 

What role does the code phyParams.BRoverlapAllowed play?
From my understanding, when this code is set to true, it allows multiple resources to be reserved in the same BR position simultaneously. Wouldn't this situation lead to collisions between resources?
I understand that to prevent such collisions, the 5G NR implements a pre-emption mechanism. Is this code used to activate that pre-emption mechanism?

If my question is unclear, please ask me to clarify. 
I always receive a lot of help from your simulator, and I'm truly thankful for that.
