### ISSUE TITLE
Question about Small scale Fading

### ISSUE THREAD

**Issue by KangHyun-Ko** [V2Xgithub/WiLabV2Xsim#35]
Hello!
Thanks to provide this great project. I have some questions about Small scale fading in this code.
Is there any small scale fading in this code?
There are shadowing, pathloss. But I can't find the small scale fading.

**Comment by V2Xgithub** [comment]
Dear KangHyun-Ko,
we assume that the impact of small-scale fading as averaged over the packet and therefore included in the PER vs. SINR curve. At the same time, we observed that approximating the PER vs. SINR curve as a threshold curve does not affect significantly the results. Some details in this paper: https://www.mdpi.com/1424-8220/22/23/9330
Best

Alessandro Bazzi, Ph.D.
Associate Professor @ DEI, Università di Bologna
Associated with WiLab, CNIT
www.alessandrobazzi.com<http://www.alessandrobazzi.com/>
Phone: +39-051-2093880
________________________________
Da: KangHyun-Ko ***@***.***>
Inviato: sabato 30 marzo 2024 13:54
A: V2Xgithub/WiLabV2Xsim ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: [V2Xgithub/WiLabV2Xsim] Question about Small scale Fading (Issue #35)


Hello!
Thanks to provide this great project. I have some questions about Small scale fading in this code.
Is there any small scale fading in this code?
There are shadowing, pathloss. But I can't find the small scale fading.

**Comment by KangHyun-Ko** [comment]
Thank you for answering my questions and providing helpful links!
