### ISSUE TITLE
Some paper's question

### ISSUE THREAD

**Issue by iamjake0918** [V2Xgithub/WiLabV2Xsim#9]
I'm sorry to bother you. i've some problems about the following paper 'Enhancing the 5G-V2X Sidelink Autonomous Mode through Full-Duplex Capabilities' . https://ieeexplore.ieee.org/document/9860814 . 
It uses this open source simulator to verify the feasibility of full-duplex performance. This can be seen in the paper. The results are very significant. I also tried to write related codes but have not yet completed it. I am curious about Figure 2 Is there any code that can be used for reference? I would like to ask the authors to give relevant replies, thank you.

**Comment by VittorioTodisco** [comment]
Hello, and thank you for your interest in our work.
Unfortunately, we cannot yet share the exact function that achieves the results from figure 2.
Nevertheless, the results shown in the paper can be obtained with some modifications to the simulator.
If you need help we can provide support.

**Comment by talukder90** [comment]
Sorry to bother you. Would you please help me how can I generate the resource allocation information by using your simulator?

**Comment by VittorioTodisco** [comment]
@talukder90 sorry to reply this late.
If you are still interested please write me or open another thread and we will try to help you.
